### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by madebymats** [Toutouwai/HannaCodeDialog#1]
Got the following error on install on ProcessWire 3.0.57 (Hanna code installed):

`Parse Error: syntax error, unexpected '[' (line 182 of /site/modules/HannaCodeDialog/HannaCodeDialog.module) 
`

**Comment by Toutouwai** [comment]
You are running ooooold version of PHP :)
But all good, so long as PW core is supporting PHP 5.3.8 then best that third-party modules do too.

Thanks for the report and fixed in latest commit.

**Comment by madebymats** [comment]
Thanks for spotting the PHP version. Everything works fine now.
