### ISSUE TITLE
Hanna Code Dialog without TextformatterHannaCode

### ISSUE THREAD

**Issue by tiefenb** [Toutouwai/HannaCodeDialog#5]
Would it be possible, to add the Hanna Code Dialog to CkEditor Fields without having the TextformatterHannaCode active for a field? I have a (very uncommon) use case where I would need this.

**Comment by Toutouwai** [comment]
It seems odd to me to try and use the module in this way when "Hanna Code" is in the title of the module, but you're not the first person who's asked about this. So in the newly released v0.4.1 I've added an option in the module config:
"Load HannaCodeDialog CKEditor plugins even if TextformatterHannaCode is not applied to field"

**Comment by adrianbj** [comment]
@Toutouwai - can you please confirm that the https://github.com/Toutouwai/HannaCodeDialog/commit/7b4ca4164372476e00aabd28d21f4b6944dfb4fa completely takes the place of the hook code you posted here: https://processwire.com/talk/topic/15902-hannacodedialog/page/5/?tab=comments#comment-208498

I think it does, but just wanted to confirm.

Thanks as always!

**Comment by Toutouwai** [comment]
@adrianbj, yes, if you use this new config option you won't need that hook any longer.

**Comment by adrianbj** [comment]
Thanks!

**Comment by tiefenb** [comment]
Thanks!
