### ISSUE TITLE
CKE plugin is not loaded in PW 3.0.184 in the AJAX Repeater

### ISSUE THREAD

**Issue by flipzoom** [Toutouwai/HannaCodeDialog#6]
After the update to ProcessWire 3.0.184 master and the corresponding update of the FieldtypeRepeater, the HannaCodeDialog plugin is no longer loaded in the RepeaterMatrix field when the repeater item is loaded dynamically via AJAX. 

https://user-images.githubusercontent.com/708183/137473365-981324c1-13cc-489d-bc81-0e6e562ba757.mp4

The problem, as I see it, is the update of the FieldtypeRepeater, which now names the JS vars differently due to the feature for a template context. (See: https://github.com/processwire/processwire/commit/d691f8e5ea9e7407c5aec7e1032a4d4a5828120e#diff-04a7a071c37f9df805d196569ec2e628a63e2279f4c14310c77f16665dfd0fbaR277-R301)

Now `InputfieldCKEditor_{fieldname}_in_{repeatername}`, instead of `InputfieldCKEditor_{fieldname}_matrix` as before.

I have implemented a quick-and-dirty fix for this. It works at least, I don't know if you have a better solution. I have added the following to the function "afterCkeRenderReady" for this purpose:

```php
protected function afterCkeRenderReady(HookEvent $event) {
    /** @var InputfieldCKEditor $inputfield */
    $inputfield = $event->object;
    $field = $inputfield->hasField;
    // Only for supported processes
    $process = $this->wire()->process;
    if(!$process || !($process instanceof ProcessPageEdit || $process instanceof ProcessProfile)) return;
    if(!$field) return;
    if(!$this->force_plugins) {
        $textformatters = $field->textformatters;
        if(!is_array($textformatters) || !in_array('TextformatterHannaCode', $textformatters)) return;
    }
    $config_name = "InputfieldCKEditor_{$field->name}";
    $config_name_matrix = "InputfieldCKEditor_{$field->name}_matrix";
    $config_name_matrix_context = "InputfieldCKEditor_{$field->name}_in_"; //@CUSTOM FIX PW > 3.0.184 (Load AJAX Repeater CKE / Template Context)
    $config = $this->wire()->config;
    $js_config = $config->js();
    foreach($js_config as $key => $value) {
        if($key === $config_name || strpos($key, $config_name_matrix) === 0 || strpos($key, $config_name_matrix_context) === 0) { //@CUSTOM FIX
            $js_config[$key]['extraPlugins'] .= ',hannadropdown,hannadialog';
            $config->js($key, $js_config[$key]);
        }
    }
}
```
This should make it work for older versions as well as for the current version. With this change, the plugin is now loaded again.

https://user-images.githubusercontent.com/708183/137474342-23b92df6-780f-434f-9502-f2c975d57e02.mp4

**Comment by Toutouwai** [comment]
Thanks, that's a good fix - I've added it in v0.4.3
